//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarsPartsReconstruccion.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Catalog
    {
        public Catalog()
        {
            this.Catalog1 = new HashSet<Catalog>();
            this.Employees = new HashSet<Employee>();
            this.ReplacedPartTracks = new HashSet<ReplacedPartTrack>();
            this.ReplacedPieces = new HashSet<ReplacedPiece>();
            this.ReplacedPieceTracks = new HashSet<ReplacedPieceTrack>();
            this.ServiceCarMiscellaneousCosts = new HashSet<ServiceCarMiscellaneousCost>();
            this.ServiceCarTracks = new HashSet<ServiceCarTrack>();
            this.ServiceMiscellaneousCosts = new HashSet<ServiceMiscellaneousCost>();
            this.ServicePartMiscellaneousCosts = new HashSet<ServicePartMiscellaneousCost>();
            this.ServiceParts = new HashSet<ServicePart>();
            this.ServicePartTracks = new HashSet<ServicePartTrack>();
            this.ServiceTracks = new HashSet<ServiceTrack>();
            this.Services = new HashSet<Service>();
            this.ReplacedParts = new HashSet<ReplacedPart>();
            this.ServiceCars = new HashSet<ServiceCar>();
            this.ServiceCars1 = new HashSet<ServiceCar>();
            this.ServiceCars2 = new HashSet<ServiceCar>();
        }
    
        public int catalogId { get; set; }
        public string catalogValue { get; set; }
        public string Description { get; set; }
        public string catalogName { get; set; }
        public Nullable<int> parentCatalog { get; set; }
    
        public virtual ICollection<Catalog> Catalog1 { get; set; }
        public virtual Catalog Catalog2 { get; set; }
        public virtual ICollection<Employee> Employees { get; set; }
        public virtual ICollection<ReplacedPartTrack> ReplacedPartTracks { get; set; }
        public virtual ICollection<ReplacedPiece> ReplacedPieces { get; set; }
        public virtual ICollection<ReplacedPieceTrack> ReplacedPieceTracks { get; set; }
        public virtual ICollection<ServiceCarMiscellaneousCost> ServiceCarMiscellaneousCosts { get; set; }
        public virtual ICollection<ServiceCarTrack> ServiceCarTracks { get; set; }
        public virtual ICollection<ServiceMiscellaneousCost> ServiceMiscellaneousCosts { get; set; }
        public virtual ICollection<ServicePartMiscellaneousCost> ServicePartMiscellaneousCosts { get; set; }
        public virtual ICollection<ServicePart> ServiceParts { get; set; }
        public virtual ICollection<ServicePartTrack> ServicePartTracks { get; set; }
        public virtual ICollection<ServiceTrack> ServiceTracks { get; set; }
        public virtual ICollection<Service> Services { get; set; }
        public virtual ICollection<ReplacedPart> ReplacedParts { get; set; }
        public virtual ICollection<ServiceCar> ServiceCars { get; set; }
        public virtual ICollection<ServiceCar> ServiceCars1 { get; set; }
        public virtual ICollection<ServiceCar> ServiceCars2 { get; set; }
    }
}
