//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarsPartsReconstruccion.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Customer
    {
        public Customer()
        {
            this.Services = new HashSet<Service>();
        }
    
        public int customerId { get; set; }
        public string customerName { get; set; }
        public string eMail { get; set; }
        public string userLogin { get; set; }
        public string address { get; set; }
    
        public virtual ICollection<Service> Services { get; set; }
    }
}
