//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarsPartsReconstruccion.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee
    {
        public Employee()
        {
            this.Suppliers = new HashSet<Supplier>();
            this.Services = new HashSet<Service>();
        }
    
        public int employeeId { get; set; }
        public string employeeName { get; set; }
        public string eMail { get; set; }
        public int positionId { get; set; }
        public string userLogin { get; set; }
    
        public virtual ICollection<Supplier> Suppliers { get; set; }
        public virtual Catalog Catalog { get; set; }
        public virtual ICollection<Service> Services { get; set; }
    }
}
