//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarsPartsReconstruccion.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class db_cars_parts_reconstructionStrConn : DbContext
    {
        public db_cars_parts_reconstructionStrConn()
            : base("name=db_cars_parts_reconstructionStrConn")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Customer> Customers { get; set; }
        public DbSet<Employee> Employees { get; set; }
        public DbSet<Piece> Pieces { get; set; }
        public DbSet<ReplacedPartTrack> ReplacedPartTracks { get; set; }
        public DbSet<ReplacedPiece> ReplacedPieces { get; set; }
        public DbSet<ReplacedPieceTrack> ReplacedPieceTracks { get; set; }
        public DbSet<ServiceCar> ServiceCars { get; set; }
        public DbSet<ServiceCarMiscellaneousCost> ServiceCarMiscellaneousCosts { get; set; }
        public DbSet<ServiceCarTrack> ServiceCarTracks { get; set; }
        public DbSet<ServiceMiscellaneousCost> ServiceMiscellaneousCosts { get; set; }
        public DbSet<ServicePart> ServiceParts { get; set; }
        public DbSet<ServicePartMiscellaneousCost> ServicePartMiscellaneousCosts { get; set; }
        public DbSet<ServicePartTrack> ServicePartTracks { get; set; }
        public DbSet<ServiceTrack> ServiceTracks { get; set; }
        public DbSet<Supplier> Suppliers { get; set; }
        public DbSet<SupplierPiece> SupplierPieces { get; set; }
        public DbSet<Part> Parts { get; set; }
        public DbSet<Catalog> Catalogs { get; set; }
        public DbSet<webpages_Membership> webpages_Membership { get; set; }
        public DbSet<webpages_OAuthMembership> webpages_OAuthMembership { get; set; }
        public DbSet<Service> Services { get; set; }
        public DbSet<UserProfile> UserProfiles { get; set; }
        public DbSet<webpages_Roles> webpages_Roles { get; set; }
        public DbSet<ReplacedPart> ReplacedParts { get; set; }
        public DbSet<SupplierPart> SupplierParts { get; set; }
    }
}
