//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarsPartsReconstruccion.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Piece
    {
        public Piece()
        {
            this.SupplierPieces = new HashSet<SupplierPiece>();
        }
    
        public int pieceId { get; set; }
        public string pieceName { get; set; }
        public string pieceDescription { get; set; }
        public Nullable<decimal> piecePrice { get; set; }
    
        public virtual ICollection<SupplierPiece> SupplierPieces { get; set; }
    }
}
