//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarsPartsReconstruccion.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReplacedPart
    {
        public ReplacedPart()
        {
            this.ReplacedPartTracks = new HashSet<ReplacedPartTrack>();
        }
    
        public int replacedPartId { get; set; }
        public int serviceCarId { get; set; }
        public Nullable<int> supplierId { get; set; }
        public Nullable<int> partId { get; set; }
        public Nullable<int> servicePartId { get; set; }
        public decimal replacedPartPrice { get; set; }
        public int statusId { get; set; }
        public string observations { get; set; }
    
        public virtual Catalog Catalog { get; set; }
        public virtual ServiceCar ServiceCar { get; set; }
        public virtual ServicePart ServicePart { get; set; }
        public virtual ICollection<ReplacedPartTrack> ReplacedPartTracks { get; set; }
        public virtual SupplierPart SupplierPart { get; set; }
    }
}
