//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarsPartsReconstruccion.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ServiceCar
    {
        public ServiceCar()
        {
            this.ServiceCarMiscellaneousCosts = new HashSet<ServiceCarMiscellaneousCost>();
            this.ServiceCarTracks = new HashSet<ServiceCarTrack>();
            this.ReplacedParts = new HashSet<ReplacedPart>();
        }
    
        public int serviceCarId { get; set; }
        public int serviceId { get; set; }
        public int carBrandId { get; set; }
        public int carModelId { get; set; }
        public Nullable<decimal> estimatedPrice { get; set; }
        public Nullable<decimal> realPrice { get; set; }
        public string serviceCarDescription { get; set; }
        public int statusId { get; set; }
        public string observations { get; set; }
    
        public virtual ICollection<ServiceCarMiscellaneousCost> ServiceCarMiscellaneousCosts { get; set; }
        public virtual ICollection<ServiceCarTrack> ServiceCarTracks { get; set; }
        public virtual Catalog Catalog { get; set; }
        public virtual Catalog Catalog1 { get; set; }
        public virtual Catalog Catalog2 { get; set; }
        public virtual Service Service { get; set; }
        public virtual ICollection<ReplacedPart> ReplacedParts { get; set; }
    }
}
