//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarsPartsReconstruccion.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ServicePartMiscellaneousCost
    {
        public int service_part_miscellaneous_costs_id { get; set; }
        public int service_part_id { get; set; }
        public decimal cost { get; set; }
        public int cost_type_id { get; set; }
        public string description { get; set; }
    
        public virtual ServicePart ServicePart { get; set; }
        public virtual Catalog Catalog { get; set; }
    }
}
