//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarsPartsReconstruccion.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Supplier
    {
        public Supplier()
        {
            this.SupplierParts = new HashSet<SupplierPart>();
            this.SupplierPieces = new HashSet<SupplierPiece>();
        }
    
        public int supplierId { get; set; }
        public string supplierName { get; set; }
        public string description { get; set; }
        public string supplierEmail { get; set; }
        public string address { get; set; }
        public Nullable<int> idRepresentative { get; set; }
    
        public virtual Employee Employee { get; set; }
        public virtual ICollection<SupplierPart> SupplierParts { get; set; }
        public virtual ICollection<SupplierPiece> SupplierPieces { get; set; }
    }
}
