//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarsPartsReconstruccion.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SupplierPiece
    {
        public SupplierPiece()
        {
            this.ReplacedPieces = new HashSet<ReplacedPiece>();
        }
    
        public int supplierPieceId { get; set; }
        public int supplierId { get; set; }
        public int pieceId { get; set; }
        public decimal price { get; set; }
        public int existence { get; set; }
    
        public virtual Piece Piece { get; set; }
        public virtual ICollection<ReplacedPiece> ReplacedPieces { get; set; }
        public virtual Supplier Supplier { get; set; }
    }
}
