//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarsPartsReconstruccion.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SupplierPart
    {
        public SupplierPart()
        {
            this.ReplacedParts = new HashSet<ReplacedPart>();
        }
    
        public int supplierPartId { get; set; }
        public int supplierId { get; set; }
        public int partId { get; set; }
        public decimal price { get; set; }
        public int existence { get; set; }
    
        public virtual ICollection<ReplacedPart> ReplacedParts { get; set; }
        public virtual Supplier Supplier { get; set; }
        public virtual Part Part { get; set; }
    }
}
